version: '3.8'
services:
  web:
    build:
      context: .
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
        - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
        - TWILIO_WHATSAPP_NUMBER=${TWILIO_WHATSAPP_NUMBER}
        - MY_WHATSAPP_NUMBER=${MY_WHATSAPP_NUMBER}
        - NEXT_PUBLIC_ZYPHRA_API_KEY=${NEXT_PUBLIC_ZYPHRA_API_KEY}
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_WHATSAPP_NUMBER=${TWILIO_WHATSAPP_NUMBER}
      - MY_WHATSAPP_NUMBER=${MY_WHATSAPP_NUMBER}
      - NEXT_PUBLIC_ZYPHRA_API_KEY=${NEXT_PUBLIC_ZYPHRA_API_KEY}
    restart: unless-stopped 